""" Nuvla CLI main script """
import logging

import typer

from .commands import create, list, remove, locate, start, user, stop
from .nuvlaio.edge import Edge


app_cli = typer.Typer()

# Add commands
app_cli.add_typer(create.app, name='create', help='Creates a new Nuvla entity: '
                                                  'edge, fleet, user')
app_cli.add_typer(list.app, name='list', help='Lists Nuvla Components')
app_cli.add_typer(remove.app, name='remove', help='Deletes a Nuvla entity: edge, '
                                                  'fleet')
app_cli.add_typer(locate.app, name='locate', help='Geo-locates an edge or fleet within a'
                                                  'country')
app_cli.add_typer(start.app, name='start', help='Runs a NuvlaEdge engine or imitates one'
                                                'when dummy')
# app_cli.add_typer(user.app, name='user')
app_cli.add_typer(stop.app, name='stop', help='Stops a NuvlaEdge engine (or fleet)')

app_cli.registered_commands += user.app.registered_commands

logging.basicConfig(
        level=logging.ERROR,
        format='[%(asctime)s] Line:%(lineno)d %(levelname)s - %(message)s',
        datefmt='%H:%M:%S'
    )


@app_cli.command(name='clear')
def clear_edges(force: bool = typer.Option(...,
                                           help='Force skip clear confirmation [Not '
                                                'recommended',
                                           prompt='You are about to decommission and '
                                                  'delete all the Edges generated by CLI,'
                                                  ' are you sure?',
                                           confirmation_prompt=True)):
    """
    Clears all the Edges instances for the user created by the CLI

    :return: None
    """
    if force:
        # Create NuvlaIO instance
        edge: Edge = Edge()
        edges_in_nuvla = edge.nuvla_api.search('nuvlabox',
                                               filter={"tags=='cli.created=True'"})

        for nuvla_edge in edges_in_nuvla.resources:

            edge.remove_edge(nuvla_edge.data.get('id'))


if __name__ == '__main__':
    app_cli()
